title: Learning About GitHub Pages
author: Kevin Oudai
email: kevinoudai@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
 This site is used to learn about GitHub Pages. It will be used as an experimental site. 
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
